### ISSUE TITLE
Please answer request for signing your Arch Linux packager key

### ISSUE THREAD

**Issue by dvzrv** [NicoHood/nicohood#1]
Hi @NicoHood! I have tried to reach you via mail a couple of times now (2021-10-23, 2021-10-30, 2021-11-19), but did not get a reply.
Please check your spam folder and make sure, that you are receiving mail from @archlinux.org.

Due to the retiring of Arch Linux main signing keys, your packager key runs the risk of becoming unusable for packaging soon.

**Comment by NicoHood** [comment]
OH, sorry. Will check that and get back to you ASAP

**Comment by NicoHood** [comment]
What is the headline of the email? I am unable to find it (for now). But it must be there, somewhere...

You can also contact me via blog cat nicohood dog de, which will land in a different folder. We can continue the discussion there. That is weird. I will also try to join the IRC tomorrow.
